### ISSUE TITLE
typo in mc_prob/3

### ISSUE THREAD

**Issue by arunwise** [friguzzi/cplint#14]
The code reads

`oprion(bar(Chart),Options,no),`

I guess it should be option.

**Comment by giuseta** [comment]
Thank you for reporting, but I cannot find in where is this typo. Could you please tell me the file and the line?

**Comment by arunwise** [comment]
This is the link to the file and line number

https://github.com/friguzzi/cplint/blob/5eca8e7f3a154b2823f62ca1103e3d71a6f12a11/prolog/mcintyre.pl#L456

**Comment by friguzzi** [comment]
fixed
