### ISSUE TITLE
Error "Exported procedure pita:randomize/2 is not defined"

### ISSUE THREAD

**Issue by hakank** [friguzzi/cplint#22]
After updating my cplint version via SWI-Prolog (pack_upgrade(cplint)), the following error is thrown for a slipcover model when running from command line on my local machine. 

"""
ERROR: /home/hakank/lib/swipl/pack/cplint/prolog/slipcover.pl:48:
        Exported procedure pita:randomize/2 is not defined
"""

And then - after running induce([train],P) - the following is thrown:

"""
N. of target clauses 196

Initial theory
Warning: Undefined procedure: pita:randomize/2
Warning:   However, there are definitions for:
Warning:         pita:randomize/1
Warning:         randomize/1
"""

**Comment by friguzzi** [comment]
Try again now, I have updated cplint

**Comment by hakank** [comment]
Hi Fabrizio.

I ran `pack_upgrade(cplint)` in SWI-Prolog a moment ago, but it says; Package "cplint" is up-to-date'.
`pack_info(cplint)` says it's version 3.1.0 if that's some clue.  I.e. I've still have this problem.

/Hakan

**Comment by friguzzi** [comment]
try with
pack_rebuild(cplint).

**Comment by hakank** [comment]
Still the same problem.

I now noticed that the latest commit in GitHub (master branch) is the "test file for initial par" commit,  from 8 hours ago. It was after updating to that version that my problem started.

**Comment by friguzzi** [comment]
It may be laoding an old version of bddem.so, try this command in swipl
`absolute_file_name(foreign(bddem),L,[solutions(all)]).`
to see where it looks for the file.
If may look for it in another folder other that the one where the pack is installed.
Have you installed also trill? If so, that may be the problem. You need to delete bddem.so from the other locations

**Comment by hakank** [comment]
I did `pack_remove(trill)` and then `pack_rebuild(cplint)` and now it works. 

Thanks!

**Comment by friguzzi** [comment]
You can reinstall pack trill, it is now compatible

**Comment by hakank** [comment]
Excellent. Thanks!
