### ISSUE TITLE
Wrong erase/1

### ISSUE THREAD

**Issue by JanWielemaker** [friguzzi/cplint#38]
https://github.com/friguzzi/cplint/blob/83f1d0ca645af85ef88eb12f58a3baa1478556b1/prolog/mcintyre.pl#L307

This is surely not good, but not used in the tests.  erase/1 takes a db ref.  I think what is meant is

```
save_samples(M,G):-
  forall(retract(M:sampled(R,Sub,V),
         assertz(M:mem(G,R,Sub,V)))).
```

**Comment by friguzzi** [comment]
Thanks, fixed in 8fea36b
