### ISSUE TITLE
Error while getting graphical result

### ISSUE THREAD

**Issue by mahyamkashani** [friguzzi/cplint#47]
Hi,
I was working with conditional inference yesterday. I have realized that the prob_bar predicate cannot recognize anymore.
I remembered I could see the histogram of the probability in the web application cplint and also in my local machine.
How can I fix this problem?

**Comment by friguzzi** [comment]
Hi,
the API for graphics has changed, see
http://friguzzi.github.io/cplint/_build/html/index.html#graphing-the-results

**Comment by friguzzi** [comment]
See also 
https://cplint.eu/example/inference/coin.swinb
and the example queries at
https://cplint.eu/example/inference/coin.pl
