### ISSUE TITLE
Rules with Disjunction in the Body

### ISSUE THREAD

**Issue by damianoazzolini** [friguzzi/cplint#48]
Rules with disjunction in the body (`;`) seems to be not supported.
```
0.1::a.
0.2::b.

q:- a ; b.
```
With `prob(q,P)` i get an error.

**Comment by friguzzi** [comment]
Yes, they are not supported in pita, they are supported in mcintyre. You can always rewrite a disjunction as two rules. Otherwise, the code that transforms the body of clauses in pita must be changed.
