### ISSUE TITLE
throwing query in gaussian example in cplint swish

### ISSUE THREAD

**Issue by Anniepoo** [friguzzi/cplint#5]
1. Browse 
   http://cplint.lamping.unife.it/example/inference/gaussian_mixture.pl

Choose the example
hist_uncond(10000,40,G).

EXPECTED: some calculation
OBSERVED: throws
is/2: Type error: `evaluable' expected, found`[]' (an empty_list)

observed on website on 1016/10/28

**Comment by friguzzi** [comment]
Annie,
I cannot reproduce it, I tried just now and no error is thrown. 
We recently changed the javascript code, can you please try 
hist_uncond(1000,40,G).
in an anonymous browser window? Or delete the cache of your browser.
Fabrizio

**Comment by Anniepoo** [comment]
works for me this morning, without clearing cache
Wonder if it's a memory leak, or timing out when under heavy load, or some such.

**Comment by friguzzi** [comment]
2016-10-29 18:43 GMT+02:00 Anne Ogborn notifications@github.com:
